"""add tables

Revision ID: 2ce5676d39ea
Revises: e44a8aa2300e
Create Date: 2023-10-28 02:36:54.707067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ce5676d39ea'
down_revision: Union[str, None] = 'e44a8aa2300e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_id'), 'character', ['id'], unique=False)
    op.create_table('group_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_config_group_id'), 'group_config', ['group_id'], unique=True)
    op.create_index(op.f('ix_group_config_id'), 'group_config', ['id'], unique=False)
    op.create_table('user_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_config_id'), 'user_config', ['id'], unique=False)
    op.create_index(op.f('ix_user_config_user_id'), 'user_config', ['user_id'], unique=True)
    op.add_column('group_user', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('group_user', sa.Column('is_banned', sa.Boolean(), nullable=True))
    op.add_column('report', sa.Column('next_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'next_date')
    op.drop_column('group_user', 'is_banned')
    op.drop_column('group_user', 'is_deleted')
    op.drop_index(op.f('ix_user_config_user_id'), table_name='user_config')
    op.drop_index(op.f('ix_user_config_id'), table_name='user_config')
    op.drop_table('user_config')
    op.drop_index(op.f('ix_group_config_id'), table_name='group_config')
    op.drop_index(op.f('ix_group_config_group_id'), table_name='group_config')
    op.drop_table('group_config')
    op.drop_index(op.f('ix_character_id'), table_name='character')
    op.drop_table('character')
    # ### end Alembic commands ###
