"""add tables

Revision ID: 2d4537ebb49f
Revises: 2ce5676d39ea
Create Date: 2023-10-28 03:02:15.051984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d4537ebb49f'
down_revision: Union[str, None] = '2ce5676d39ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_config', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('group_config', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('group_config', 'updated_at')
    op.drop_column('group_config', 'created_at')
    # ### end Alembic commands ###
