"""change name character_id to mentor_id

Revision ID: 4b7ba426d4f7
Revises: 2bb107defd6d
Create Date: 2023-10-28 21:31:55.099196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b7ba426d4f7'
down_revision: Union[str, None] = '2bb107defd6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_config', sa.Column('mentor_id', sa.Integer(), nullable=False))
    op.drop_column('user_config', 'character_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_config', sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('user_config', 'mentor_id')
    # ### end Alembic commands ###
