"""[fix] reportの達成度を100段階に変更

Revision ID: 8e87002c104b
Revises: c6098d662989
Create Date: 2023-10-28 07:41:59.409012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e87002c104b'
down_revision: Union[str, None] = 'c6098d662989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('achieved_score', sa.Integer(), nullable=True))
    op.drop_column('report', 'is_achieved')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('is_achieved', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('report', 'achieved_score')
    # ### end Alembic commands ###
