"""delete character table-1

Revision ID: 95e8811f9405
Revises: 8e87002c104b
Create Date: 2023-10-28 17:40:55.105731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95e8811f9405'
down_revision: Union[str, None] = '8e87002c104b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_config_character_id_fkey', 'user_config', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('user_config_character_id_fkey', 'user_config', 'character', ['character_id'], ['id'])
    # ### end Alembic commands ###
