"""add column: help_required

Revision ID: 9d6a596874a3
Revises: a460e6509c5e
Create Date: 2023-10-29 02:18:48.582614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d6a596874a3'
down_revision: Union[str, None] = 'a460e6509c5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('help_required', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'help_required')
    # ### end Alembic commands ###
