"""Add Index to Report.user_id

Revision ID: e44a8aa2300e
Revises: a723a5a9acb9
Create Date: 2023-10-28 02:10:28.703075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e44a8aa2300e'
down_revision: Union[str, None] = 'a723a5a9acb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_report_user_id'), 'report', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_user_id'), table_name='report')
    # ### end Alembic commands ###
