"""add goal to userconfig

Revision ID: f160bba0ff89
Revises: 77e0d11191c0
Create Date: 2023-10-29 00:58:17.076691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f160bba0ff89'
down_revision: Union[str, None] = '77e0d11191c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_config', sa.Column('goal', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_config', 'goal')
    # ### end Alembic commands ###
